### ISSUE TITLE
TABLE draft (scoped)

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/eosio-wps#10]

**Comment by DenisCarriere** [comment]
Implemented

## TABLE `drafts`

**scope**: `proposer`

- `{name} proposer` - proposer of proposal
- `{name} proposal_name` - proposal name
- `{string} title` - proposal title
- `{asset} budget` - monthly budget payment request
- `{uint8_t} duration` - monthly budget duration (maximum of 6 months)
- `{map<name, string>} proposal_json` - a sorted container of <key, value>

### example

```json
{
  "proposer": "myaccount",
  "proposal_name": "mywps",
  "title": "My WPS",
  "budget": "500.0000 EOS",
  "duration": 1,
  "proposal_json": [
    { "key": "category", "value": "other" },
    { "key": "region", "value": "global" }
  ]
}
```
