### ISSUE TITLE
Consider adding an “activate on next cycle” option

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/eosio-wps#12]

**Comment by DenisCarriere** [comment]
Added `next` param to `activate` ACTION

## ACTION `activate`

Activate WPS proposal

**authority**: `proposer`

**ram_payer**: `get_self()`

- `{name} proposer` - proposer
- `{name} proposal_name` - proposal name
- `{bool} [next=false]` - (true/false) activate proposal at the next voting period

```bash
cleos push action eosio.wps activate '["myaccount", "mywps", false]' -p myaccount
```
