### ISSUE TITLE
add available budget (pool) to contract

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/eosio-wps#5]

**Comment by DenisCarriere** [comment]
Basic implementation using `settings` & `state`

## TABLE `settings`

- `{int16_t} [vote_margin=15]` - minimum BP vote margin threshold to reach for proposals
- `{asset} [deposit_required="100.0000 EOS"]` - deposit required to active proposal
- `{uint64_t} [voting_interval=2592000]` -  election interval in seconds
- `{asset} [max_monthly_budget="50000.0000 EOS"]` - maximum monthly budget

### example

```json
{
  "vote_margin": 15,
  "deposit_required": "100.0000 EOS",
  "voting_interval": 2592000,
  "max_monthly_budget": "50000.0000 EOS"
}
```

## TABLE `state`

- `{time_point_sec} current_voting_period` - current voting period
- `{asset} [liquid_deposits="0.0000 EOS"]` - liquid deposits
- `{asset} [locked_deposits="0.0000 EOS"]` - locked deposits
- `{asset} [available_funding="0.0000 EOS"]` - available funding

### example

```json
{
  "current_voting_period": "2019-11-01T00:00:00",
  "liquid_deposits": "100.0000 EOS",
  "locked_deposits": "200.0000 EOS",
  "available_funding": "50000.0000 EOS",
}
```
