### ISSUE TITLE
add activated date in proposal

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/eosio-wps#8]

**Comment by DenisCarriere** [comment]
Implemented, added `start` & `end` dates to `proposals` TABLE

## TABLE `proposals`

- `{name} proposer` - proposer of proposal
- `{name} proposal_name` - proposal name
- `{string} title` - proposal title
- `{asset} budget` - monthly budget payment request
- `{uint8_t} duration` - monthly budget duration (maximum of 6 months)
- `{map<name, string>} proposal_json` - a sorted container of <key, value>
- `{time_point_sec} start` - start of voting period (UTC)
- `{time_point_sec} end` - end of voting period (UTC)

### example

```json
{
  "proposer": "myaccount",
  "proposal_name": "mywps",
  "title": "My WPS",
  "budget": "500.0000 EOS",
  "duration": 1,
  "proposal_json": [
    { "key": "category", "value": "other" },
    { "key": "region", "value": "global" }
  ],
  "start": "2019-11-05T12:10:00",
  "end": "2019-12-01T00:00:00"
}
```
